package CORBA_Server;

import edu.kit.ibt.manv.server.corba.FilterImpl;


/**
* CORBA_Server/FilterDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server_PublishSubscribe.idl
* Donnerstag, 11. Februar 2010 01:54 Uhr MEZ
*/

public class FilterDefaultFactory implements FilterValueFactory {

  public Filter init (CORBA_Server.Subscriber s, int registered_events)
  {
    return new FilterImpl (s, registered_events);
  }

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new FilterImpl ());
  }
}
