Diplomarbeit.pdf: Diplomarbeit.tex Titel.tex Vorwort.tex Danksagung.tex Abstract.tex Einleitung.tex Grundlagen.tex Stand_der_Technik.tex Entwurf.tex Praktische_Realisierung.tex Ergebnisse.tex Diskussion.tex Ausblick.tex
	pdflatex  Diplomarbeit Titel.tex Vorwort.tex Danksagung.tex Abstect.tex Einleitung.tex Grundlagen.tex Stand_der_Technik.tex Entwurf.tex Praktische_Realisierung.tex Ergebnisse.tex Diskussion.tex Ausblick.tex Diplomarbeit.bib
	bibtex Diplomarbeit
	pdflatex  Diplomarbeit Titel.tex Vorwort.tex Danksagung.tex Abstect.tex Einleitung.tex Grundlagen.tex Stand_der_Technik.tex Entwurf.tex Praktische_Realisierung.tex Ergebnisse.tex Diskussion.tex Ausblick.tex Diplomarbeit.bib
	pdflatex  Diplomarbeit Titel.tex Vorwort.tex Danksagung.tex Abstect.tex Einleitung.tex Grundlagen.tex Stand_der_Technik.tex Entwurf.tex Praktische_Realisierung.tex Ergebnisse.tex Diskussion.tex Ausblick.tex Diplomarbeit.bib

clean:
	rm -f Diplomarbeit.pdf *.aux *.bbl *.dvi

all: Diplomarbeit.pdf
