#include "Common.idl"

module CORBA_Server
{
  // Methoden um den Server über Ereignisse im Node-Netzwerk zu informieren.
  interface Incoming
  {   
    // node_id:		ID der Node von der die Daten kommen
    // group_id:	ID der Gruppe zu der die Node gehört
    // puls: 		Puls pro Minute
    // breathing:	Atmung pro Minute
    void notify_data(in Common::CORBA_DataMessage data);
    
  	// node_id: 	ID der Node die das Ereignis ausgelöst hat
  	// group_id: 	ID der Gruppe zu der die Node gehört
  	// etype:		Art des Ereignisses
  	void notify_event(in Common::CORBA_EventMessage event);
  };
};
